### PR TITLE
More Resources by capSilver

### PR DESCRIPTION
**Pull request by takuhii**
Uploaded by Takuhii, created by capSilver

### CODE REVIEW

**Comment by ONElua** [comment]
Upload these missing resources, before approving this PR

Missing: GOWCHAINSOLYMPUS.jpg
Missing: GOWGHOSTSPARTA.jpg
Missing: GKHISTORY.jpg
Missing: GTACHINATOWNWARS.jpg
Missing: GTALIBERTYCITYSTORIES.jpg
Missing: GTAVICECITYSTORIES.jpg
Missing: GROWLANCERWOT.jpg
Missing: GUNSHOWDOWN.jpg
Missing: GURUMINMA.jpg
Missing: HALFMINUTEHEROCS.jpg
Missing: HALFMINUTEHERO2.jpg
Missing: HEXYSFORCE.jpg
Missing: JEANNEDARC.jpg
Missing: JUICED2.jpg
Missing: KILLZONELIBERATION.jpg
Missing: KHBBS.jpg
Missing: KINGDOMOFPARADISE.jpg
Missing: LEGOSTARWARSORIGINALTRILOGY.jpg
Missing: LITTLEBIGPLANET.jpg
Missing: LOCOROCO1.jpg
Missing: LOCOROCO2CS.jpg
Missing: MANHUNT2.jpg
Missing: MARVELULTIMATEALLIANCE.jpg
Missing: MEMYKATAMARI.jpg
Missing: MEDIEVILRESSURECTION.jpg

Missing: PATAPONCS2.jpg
Missing: PATAPONCS2.zip
Missing: capSilver

Missing: PATAPONCS3.jpg
Missing: PATAPONCS3.zip
Missing: capSilver

**Comment by takuhii** [comment]
done :) Sorry

**Comment by takuhii** [comment]
I'm takin a break after this, making too many mistakes, and I have all of capSilvers PSX stuff to do yet :/

**Comment by ONElua** [comment]
no problem
I am grateful to you.
I have not had time and I also have many pending bubbles to upload

**Pull request merged**
