### PR TITLE
New Resources by Takuhii

### PR DESCRIPTION
**Pull request by takuhii**
Updated games assets for God of War: Chains of Olympus and Ghost of Sparta.

New Assets for DaedalusX64 N64 Emulator

### CODE REVIEW

**Comment by ONElua** [comment]
Sorry
Now you must add the info in New Database.json
the previews in GAMEID.jpg 128 * 128

**Comment by takuhii** [comment]
Ah ok... Could you remind me on how to keep my assets in sync with yours?

**Comment by ONElua** [comment]
im upload your Resources without Mac files...
please wait

**Comment by takuhii** [comment]
My bad, I'll fix it. Stupid Mac files :)

**Comment by ONElua** [comment]
Thanks
PD: Check out the new json
https://github.com/ONElua/VitaBubbles/commit/93515aab5b51c832f1b3f1a93375445b698f61f1

**Pull request closed without merging**
